### PR TITLE
Zdb deployment overview

### PR DESCRIPTION
**Pull request by robvanmieghem**
@xmonader @muhamadazmy Is this correct ( especially the vm's part)?

### CODE REVIEW

**Comment by muhamadazmy** [comment]
ZDB on zero-os don't run inside VMS. Here is all what i know about qsfs and how it works

- ZDBs are services maintained by zos itself, and runs inside containers just for isolation. Each instance of ZDB owns a single HDD and it has exclusive access to it. So creating a new zdb namespace only costs the space it reserves.
- A single instance of qsfs (also runs encapsulated in a container) consists of the followins:
  - zdb-fs instance, this what creates the fuse mountpoint, all the data is stored in the local zdb insntace
  - note that the zdb instance that is part of the qsfs runs inside the qsfs container and has nothing to do with other zdb instances maintained by zos to server zdb namespaces for other users.
  - zstore, this one have many hooks with the zdb instance to push/get zdb db segement files from remote zdbs.

**Review by muhamadazmy — CHANGES_REQUESTED** [review]
ZDB on zos don't run inside VMs. while this is a tiny detail it can be very confusing. Please check the other comment for an overview of how things work together.

**Comment by xmonader** [comment]
Indeed @muhamadazmy is correct, I believe i mislead you by the general setup of zstor + zdbcache + 0-db-fs and having backend zdbs configured manually on VMs outside of zos https://github.com/threefoldfoundation/fediverse/blob/35bc4a824246a4726349d5b29df9d09795fea0ab/docs/qsfs_manual_setup.md


in ZOS indeed, the qsfs workload gets populated by configs including the `zdb backends` https://github.com/threefoldtech/zos/blob/53f79f6d0757df3c66382411dc7ad10de07b66cf/pkg/gridtypes/zos/qsfs.go, these zdb backends can be on other nodes, after deployment of zdb workload you receive ips/port to be able to reuse it in qsfs workloads

**Comment by robvanmieghem** [comment]
Thanks, I'll modify the diagram to be containers instead of VM's

**Pull request merged**
